# Travis documentation for Android project builds:
# https://docs.travis-ci.com/user/languages/android

language: android
android:
  components:
    - build-tools-26.0.1
    - android-26
script:
  - ./gradlew check jacoco assemble
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.m2