# Travis documentation for Android project builds:
# https://docs.travis-ci.com/user/languages/android

language: android
android:
  components:
    - build-tools-30.0.0
    - android-230
script:
  - ./gradlew check jacoco assemble
  - bash <(curl -s https://codecov.io/bash)
before_install:
  - yes | sdkmanager "platforms;android-30"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
